#include "drv.h"
#include "base.h"
#include "cdserdef.h"
#include "gsp.h"
#include "ofbdefs.h"
#include "impresio.h"
#include "csr.h"
#include "Sap.h"
#include "tesoro.h"
#include "Hcommstd.h"
#include "presupuesto.h"
#include "descuento.h"
#include "pickdrv.h"
#include "bonif.h"	
#define REST_REG "REGIONES:"
#define REST_PRV "PROVINCIAS:"
#define REST_SUC "SUCURSALES:"
#define REST_CLI "CLIENTES:"
#define REST_UP "UP:"
#define REST_PRD "PRODUCTOS:"
#define REST_ESP "ESPECIES:"
