#include "sucuvirt.h"
#include "commdef.h"
#include "hcommstd.h"
#include "ofbdefs.h"
#include "hcomm.h"
#include "tlr.h"
#include "base.h"
#include "cdserdef.h"
#include "drv.h"
#include "giros.h"
#include "sap.h"
#include "Impresio.h"
#define MENSAJES_CIERRE "SI"
#define STATUS_UP_ANULADO 100
