/****x* Pendientes de agrupación/DEF:includes:afip
* NOMBRE
*   DEF:includes:afip
* DESCRIPCION
*   Comportamiento del objeto (obligatorio)
* IMPACTOS
*   Otros objetos que deberán ser analizados al modificar el objeto actual
* REFERENCIADO POR
*   Objetos que llaman al objeto documentado (obligatorio)
* DOCUMENTACION
*   Documentación relevante que deberá ser actualizada por la modificación de la rutina
* SOURCE
*/

#define CantImp       20
#define ImpuestosFin  999
#define ImpuestosSel  1
#define CuitGenerico  0
#define CuitSociedad  1
#define CuitPerFisica 2

/*******/
