/****x* Pendientes de agrupación/DEF:includes:batch
* NOMBRE
*   DEF:includes:batch
* DESCRIPCION
*   Comportamiento del objeto (obligatorio)
* IMPACTOS
*   Otros objetos que deberán ser analizados al modificar el objeto actual
* REFERENCIADO POR
*   Objetos que llaman al objeto documentado (obligatorio)
* DOCUMENTACION
*   Documentación relevante que deberá ser actualizada por la modificación de la rutina
* SOURCE
*/

#include "base.h"

;Reentry function for batch rt                 (1=supported, 0=not supported)
#define		BATCH_REENTRY  0

/*******/
