/****x* Pendientes de agrupación/DEF:include:DOCS
* NOMBRE
*   DEF:include:DOCS
* DESCRIPCION
*   Comportamiento del objeto (obligatorio)
* ENTRADAS
*   Parámetros de entrada de la rutina, sean argumentos o campos que tiene en cuenta
* SALIDAS
*   Campos modificados como resultado o returns cuyos valores sean no triviales
* IMPACTOS
*   Otros objetos que deberán ser analizados al modificar el objeto actual
* REFERENCIADO POR
*   Objetos que llaman al objeto documentado (obligatorio)
* DOCUMENTACION
*   Documentación relevante que deberá ser actualizada por la modificación de la rutina
* SOURCE
*/
# ifndef	DOCS_H
# define	DOCS_H

# define	DOC_LINE_S	40
# define	FIN_HEADER	10

# define	COM_FOOTER	0

# endif


/*******/
