/****x* Pendientes de agrupación/DEF:include:NOWAIT
* NOMBRE
*   DEF:include:NOWAIT
* DESCRIPCION
*   Comportamiento del objeto (obligatorio)
* ENTRADAS
*   Parámetros de entrada de la rutina, sean argumentos o campos que tiene en cuenta
* SALIDAS
*   Campos modificados como resultado o returns cuyos valores sean no triviales
* IMPACTOS
*   Otros objetos que deberán ser analizados al modificar el objeto actual
* REFERENCIADO POR
*   Objetos que llaman al objeto documentado (obligatorio)
* DOCUMENTACION
*   Documentación relevante que deberá ser actualizada por la modificación de la rutina
* SOURCE
*/
# ifndef NOWAIT_H
# define NOWAIT_H

# define KEY_OUT   	-4			/* used in no-wait I/O */
# define RESET_OUT 	-3
# define TIMED_OUT  -2

#endif


/*******/
